### ISSUE TITLE
[Admin] New User Backend

### ISSUE THREAD

**Issue by lvayne1** [clmnshn28/Aquencher1.0#31]
As an admin, I need the "Add New User" feature to connect with the backend for user creation. This includes implementing the API endpoint, validating user input, handling errors, and updating the database.

**Comment by otaKenneth** [comment]
[try this](https://stackoverflow.com/questions/76920065/why-do-i-get-error-csrf-token-mismatch-react-18-spa-with-laravel-10-api)
